use crate::MonitorConfig;

pub fn get_default_monitors() -> Vec<MonitorConfig> {
    vec![
        MonitorConfig {
            id: "def_1".to_string(),
            name: "User Temp".to_string(),
            path: "%LOCALAPPDATA%\\Temp".to_string(),
            threshold: 1024.0,
            enabled: true,
            notify: false,
        },
        MonitorConfig {
            id: "def_2".to_string(),
            name: "System Temp".to_string(),
            path: "C:\\Windows\\Temp".to_string(),
            threshold: 1024.0,
            enabled: true,
            notify: false,
        },
        MonitorConfig {
            id: "def_3".to_string(),
            name: "Spotify Data".to_string(),
            path: "%LOCALAPPDATA%\\Spotify\\Data".to_string(),
            threshold: 1024.0,
            enabled: true,
            notify: false,
        },
        MonitorConfig {
            id: "def_4".to_string(),
            name: "Spotify Storage".to_string(),
            path: "%LOCALAPPDATA%\\Spotify\\Storage".to_string(),
            threshold: 2048.0,
            enabled: true,
            notify: false,
        },
        MonitorConfig {
            id: "def_5".to_string(),
            name: "Google Chrome Cache".to_string(),
            path: "%LOCALAPPDATA%\\Google\\Chrome\\User Data\\Default\\Cache".to_string(),
            threshold: 500.0,
            enabled: true,
            notify: false,
        },
        MonitorConfig {
            id: "def_6".to_string(),
            name: "Discord Cache".to_string(),
            path: "%APPDATA%\\discord\\Cache".to_string(),
            threshold: 500.0,
            enabled: true,
            notify: false,
        },
        MonitorConfig {
            id: "def_7".to_string(),
            name: "VS Code Cache".to_string(),
            path: "%APPDATA%\\Code\\Cache".to_string(),
            threshold: 500.0,
            enabled: true,
            notify: false,
        },
        MonitorConfig {
            id: "def_8".to_string(),
            name: "NVIDIA GL Cache".to_string(),
            path: "%LOCALAPPDATA%\\NVIDIA\\GLCache".to_string(),
            threshold: 1024.0,
            enabled: true,
            notify: false,
        },
        MonitorConfig {
            id: "def_9".to_string(),
            name: "NPM Cache".to_string(),
            path: "%LOCALAPPDATA%\\npm-cache".to_string(),
            threshold: 1024.0,
            enabled: true,
            notify: false,
        },
        MonitorConfig {
            id: "def_10".to_string(),
            name: "Yarn Cache".to_string(),
            path: "%LOCALAPPDATA%\\Yarn\\Cache".to_string(),
            threshold: 1024.0,
            enabled: false,
            notify: false,
        },
        MonitorConfig {
            id: "def_11".to_string(),
            name: "Recycle Bin".to_string(),
            path: "C:\\$Recycle.Bin".to_string(),
            threshold: 1000.0,
            enabled: true,
            notify: false,
        },
        MonitorConfig {
            id: "def_12".to_string(),
            name: "Windows Minidump".to_string(),
            path: "C:\\Windows\\Minidump".to_string(),
            threshold: 500.0,
            enabled: true,
            notify: false,
        },
        MonitorConfig {
            id: "def_13".to_string(),
            name: "Windows Update Downloads".to_string(),
            path: "C:\\Windows\\SoftwareDistribution\\Download".to_string(),
            threshold: 2048.0,
            enabled: true,
            notify: false,
        },
        MonitorConfig {
            id: "def_14".to_string(),
            name: "Windows Installer".to_string(),
            path: "C:\\Windows\\Installer".to_string(),
            threshold: 500.0,
            enabled: true,
            notify: false,
        },
        MonitorConfig {
            id: "def_15".to_string(),
            name: "DriverStore".to_string(),
            path: "C:\\Windows\\System32\\DriverStore\\FileRepository".to_string(),
            threshold: 500.0,
            enabled: true,
            notify: false,
        },
    ]
}
